import { User, Vehicle, Booking, Maintenance, Agency, PricingClass, PricingRule, SystemAlert } from './types';

export const INITIAL_AGENCIES: Agency[] = [
  {
    id: 'agency_1',
    name: 'Elite Motors',
    ownerName: 'Jonathan Sterling',
    email: 'agency@rentigo.com',
    phone: '+91 99999 00000',
    address: '782 Corporate Parkway, Suite 400, Financial District',
    city: 'Surat',
    zip: '395007',
    fleetSize: '21-50',
    taxId: 'GSTIN-EM9022',
    tier: 'Premium',
    status: 'Verified',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDnJcTbfQCQYY3U5MFbPXAa1tHxFZKxJB82uqlp-B74V_0CTbrXtjz4_2XkrJtNKyTrb6yGJvPo_-ENIq6ZwTDmvqbdYzi1p2ZFU7FH53lnRhxPiSkXjQH2f830p1XT9EnBjRYeXbcr0MvWOLXnvjPRENaEbsLID-L2w--UIX7-Nmrevh4xw5doE1gSgJ1fsqpzf6Bt36QLBDK-n6Sx6TNSr6UrOoINUyQ0DMdfwXmveug94BGa6PEvqz1FXClnpwrwh5M9mYdGFdcI'
  },
  {
    id: 'agency_2',
    name: 'Skyline Ventures',
    ownerName: 'Robert Chen',
    email: 'robert.chen@skyline.com',
    phone: '+91 98765 43210',
    address: '402 Skyline Arcade, SG Highway',
    city: 'Ahmedabad',
    zip: '380015',
    fleetSize: '50+',
    taxId: 'GSTIN-SV8841',
    tier: 'Premium',
    status: 'Verified',
  },
  {
    id: 'agency_3',
    name: 'Blue Ridge Rentals',
    ownerName: 'Elena Rodriguez',
    email: 'elena.r@blueridge.com',
    phone: '+91 97654 32109',
    address: '150 West Junction Way, Alkapuri',
    city: 'Vadodara',
    zip: '390007',
    fleetSize: '50+',
    taxId: 'GSTIN-BR2019',
    tier: 'Standard',
    status: 'Verified',
  },
  {
    id: 'agency_4',
    name: 'Urban Lux Drive',
    ownerName: 'Marcus Thorne',
    email: 'marcus.t@urbanlux.com',
    phone: '+91 96543 21098',
    address: '80 Kalawad Road Bypass Crossing',
    city: 'Rajkot',
    zip: '360005',
    fleetSize: '50+',
    taxId: 'GSTIN-UL4412',
    tier: 'Premium',
    status: 'Verified',
  },
  {
    id: 'agency_5',
    name: 'Coastline Rentals',
    ownerName: 'Sarah Jenkins',
    email: 's.jenkins@coastline.com',
    phone: '+91 95432 10987',
    address: '120 Dumas Road, near Airport Circle',
    city: 'Surat',
    zip: '395007',
    fleetSize: '21-50',
    taxId: 'GSTIN-CR5510',
    tier: 'Standard',
    status: 'Verified',
  }
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'veh_1',
    name: 'Tesla Model 3',
    type: '4-Wheeler',
    year: 2023,
    fuelType: 'Electric',
    transmission: 'Automatic',
    rateDay: 120,
    rateWeek: 750,
    rateMonth: 2500,
    status: 'Available',
    plateNo: 'ABC-1234',
    agencyId: 'agency_1',
    agencyName: 'Elite Motors',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC842OrLsEaVFsCsJWoRKHllgwFNZ_-E-ZsVWgoIDJvVnbclSU-OYa09o7S-aHW-xFpKXc-7moz_Y9kxMtpS03Ns0J1O0rHK7KYHfItVnHaBsH7AzDNWSe7OOMQLgSxDc-SKb54YYkfXjSKYTgX70hJLE80LZ9GDaQctgR3LE73iDj7hZD_7bUZsVL2uBK3JYF9eur73db_OJWduIWkso-rdz0gsi7w9-D-DRuRuO1czCvScKMWhLscWwIo4H1Pn2f3rz40uRIw-7XN',
    approved: true,
    maintenanceBlocked: false,
    notes: 'Premium high-performance electric vehicle.'
  },
  {
    id: 'veh_2',
    name: 'Range Rover Sport',
    type: '4-Wheeler',
    year: 2022,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    rateDay: 245,
    rateWeek: 1500,
    rateMonth: 5500,
    status: 'Available',
    plateNo: 'XYZ-7788',
    agencyId: 'agency_3',
    agencyName: 'Blue Ridge Rentals',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBUslbiyxEXtoZS3TIKbKrakBQAhk6EpN20RjLvfrPZNRGbH1-ZJwf6hO33N0r5hICxWz8pofOhAXaVQ-KbxvbJa-mAkUUBrRCQdwMofvgiieGu7OvkAoeqlX1uVxzIIeAiUnu0IkwZyMCQ81hxoO3ufporqixnLGw6RtblAYkfuG6JhuPwAblMkRcbNFUu5AJIEZ-CYr3sakNsAv-RM0JbIdF4vOWOhHRvZcArHd-m3E6rY_lLj7XPykAx-b8QOPK5L8xOrmn7iXkk',
    approved: true,
    maintenanceBlocked: false,
    notes: 'High clearance executive luxury SUV'
  },
  {
    id: 'veh_3',
    name: 'Mercedes Benz C-Class',
    type: '4-Wheeler',
    year: 2023,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    rateDay: 180,
    rateWeek: 1100,
    rateMonth: 4200,
    status: 'Available',
    plateNo: 'LUX-5500',
    agencyId: 'agency_1',
    agencyName: 'Elite Motors',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAeVr8BLXp6g3Bz9DCMJc5bkAt6sF_9Qq1a3CbpYDbIWnU7IM-XqYkAdPgnihOML3_J3Ho6YSK_JNX2xTh1UtGUsgr0vDAffS76cp0BIayUzFWtT7DwUd4doFi_f25PgctsB9ypTSRh-AdIX6TB61QA_9IxKtrDZZzQI24B4MNDUauGWFspvh0E3O9amd6ttRB4s0goQUxgpysMo1FY6ZpLnsY0PnJXTzeZAZ7b_RnEXodF8WcujQr1DrF17HydxscZHtIzR1GJANxO',
    approved: true,
    maintenanceBlocked: false,
    notes: 'Aesthetic executive saloon with class-leading luxury parameters.'
  },
  {
    id: 'veh_4',
    name: 'BMW 5 Series',
    type: '4-Wheeler',
    year: 2023,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    rateDay: 140,
    rateWeek: 900,
    rateMonth: 3200,
    status: 'Maintenance',
    plateNo: 'V-8821',
    agencyId: 'agency_1',
    agencyName: 'Elite Motors',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAr2Yvuy1h_uVWDigpHebt280CDavg9BKJj8KQm5x3IbWPn9dI5cfwuXgvshhTrACd9Xe0a9qON_PRFtGv4N0ualwVFHbpTLa_w3NuK8Ud4cNJWtLhwMSEpoi2wW5ZkMg8SiD_xv1igIf_Eok_CcM0fCOPAbBlCzTa7nWzLxBiB4nJK2BQUzpyq-4UM_tZFbYCXFSSaNQlbwovfqMD-3E8mXkg2JegV6fQjnU6Cd8fJRt0Fr173fGHq71wQ0B8WbkmYUmNICZsbOAhs',
    approved: true,
    maintenanceBlocked: true,
    notes: 'Premium business-class executive drive.'
  },
  {
    id: 'veh_5',
    name: 'Audi Q7',
    type: '4-Wheeler',
    year: 2022,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    rateDay: 210,
    rateWeek: 1300,
    rateMonth: 4800,
    status: 'Maintenance',
    plateNo: 'V-7422',
    agencyId: 'agency_4',
    agencyName: 'Urban Lux Drive',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBrT6m7yN-hAcivmUKdXYg-D9ysdEzMEGjpXVr1MtLtghuLzoOMYgtz-6004fokDnUh9zAe57JoEQ80fpBlu0bzd1nf4F0D_NdvO31HOCdtI0s0_6r02-eXYSVWnQxMbY-Nkl9REU8FeUYXaDrjS66xbzKg1B0LZcNTbpJBo5PkAcTMSyoc5tUTqb7zE-68B--7yTpzWhebWWJTae9ym8udvvaFgHHH0hWIrNm2oJo0hEOVrwYkFtggxG-aDumyiCIs8aYiRmPHTXeF',
    approved: true,
    maintenanceBlocked: false,
    notes: 'Ultimate premium utility and performance.'
  },
  {
    id: 'veh_6',
    name: 'BMW X5 xDrive',
    type: '4-Wheeler',
    year: 2023,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    rateDay: 150,
    rateWeek: 1000,
    rateMonth: 3800,
    status: 'Rented',
    plateNo: 'NY-55-RG-0199',
    agencyId: 'agency_4',
    agencyName: 'Urban Lux Drive',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDaMqUY0z6CFqh79UQSIrjIQxIHcRE1TgpOHM-nYMVtK5E_d_SdQxzXXZD-_dLnppl3-PzJa1-OtA2oKJWUZLSR08LhKlEmuwK5_7EoOaUq7uoc-9vQWVIn8OO5DsDczWXrRPoSwU_k6RtQtuwbp0Cyha4v3xudcfB979LVvZzuiup9bxDeSbLjoUxC9fYoDBsrSkSATJDEbsrRcZ8wvJDRQYFLWjMrniNBx6Nl_7MAdX1x65TsHUh5kGLWOPv1B0t_Vu-gtSj2io-l',
    approved: true,
    maintenanceBlocked: false,
  },
  {
    id: 'veh_7',
    name: 'Tesla Model Y',
    type: '4-Wheeler',
    year: 2023,
    fuelType: 'Electric',
    transmission: 'Automatic',
    rateDay: 130,
    rateWeek: 850,
    rateMonth: 3100,
    status: 'Rented',
    plateNo: 'FLT-9001-Z',
    agencyId: 'agency_1',
    agencyName: 'Elite Motors',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB1Oxr27qU3y8EP3O3wd5tN-ND3qaO6RxoXAEwl0H3bsd15TEcDxoXJJQV_q9Pa5eqC-2tmF6dqORoEQ6yXvPgSsXua1JfoK_C_g_MlCNUshUC6LC68yxIyH6-yxrIGtCd-ON5obKIcf_jY7XbzML3LAozjuyiQT2uh4YVrnzjcxKynjeVdcbgXXZjzTqpFK7DzcDuYR4EExUU3gq49iU7tnDKjc96aiT2s--MOkRPC4qnHzfS7tqiSh81rUR0gshqgM1a0DpB0fqDo',
    approved: true,
    maintenanceBlocked: false,
  },
  {
    id: 'veh_8',
    name: 'Toyota RAV4 Hybrid',
    type: '4-Wheeler',
    year: 2023,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    rateDay: 85,
    rateWeek: 540,
    rateMonth: 1950,
    status: 'Rented',
    plateNo: 'FLT-4431-B',
    agencyId: 'agency_1',
    agencyName: 'Elite Motors',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDDC61M-J_huluUkoKCs-nBpCEmHHSj6UWDBgCKALq6qz9EKyrC6w22Fa6GiUgaYMRUqkvbTP1ltwUO-Rp_xBMGy_7wFV-3e9gUaH4-audEtXx50DLHf8NQch2rif_b5zdo_6CVUwabazE-WfdLrvgUfWnF2XaSRroPB6WPSqvfBZTwQ73qfy4rQM32K_S18qCyx9SHEXgcmPFbD_1YwSqtBgmDmyEsYaduFiSoozyRJhCo-WvcAsjflw_QDYXAsjjqQ19mqbWCWouG',
    approved: true,
    maintenanceBlocked: false,
  },
  {
    id: 'veh_9',
    name: 'Volkswagen Golf',
    type: '4-Wheeler',
    year: 2022,
    fuelType: 'Petrol',
    transmission: 'Manual',
    rateDay: 65,
    rateWeek: 420,
    rateMonth: 1550,
    status: 'Available',
    plateNo: 'FLT-2210-H',
    agencyId: 'agency_2',
    agencyName: 'Skyline Ventures',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCFk5OW8S6O_XZ81k1vYhGBjzBJmdlxSooS-CjI3A9mX34AJqy89k1oQZuttEgxYk-4yF-V6tjqbU67N-2BrCKPB9_4QtnAiEMlJOglX9803T4BjuH6JDSpNHVacu7SEY8sw392Ij6E4l5GdomU7H5wBL3ixvDnmL9G7cHhbpbit3pwLFoZMEKiTQFFe0zN_q3rWMVshu9vjsT02cbg_icDezWa9hDA9J1x3Okay3KNqwbN-vw6Du1xEkr3iZEiyblOEusUiwDCufrZ',
    approved: true,
    maintenanceBlocked: false,
  },
  {
    id: 'veh_10',
    name: 'Mercedes-Benz E-Class',
    type: '4-Wheeler',
    year: 2024,
    fuelType: 'Electric',
    transmission: 'Automatic',
    rateDay: 120,
    rateWeek: 750,
    rateMonth: 2800,
    status: 'Available',
    plateNo: 'FLT-7829-X',
    agencyId: 'agency_2',
    agencyName: 'Skyline Ventures',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBIFPe7ZWBo2GLA2WRDVJcGGc4POe4nMyM5UKmVLZOXdp8lLwjLbULBF91LErGyHH5He5ef-oCTNcBvod0cJRMRq29PkLa30tpXIGyr1ZiIIsaq-pxov-OuaWJrGzHnQzsRokyScbnoF0dkoHWeTGADsMA6-MMSw3137sdzCS5El1-mR_hayaEF7e3_VludUS1wu6Imasl-jS8woFrZ75slIHCvhZwftzId7SM6FQ84aCpU9dBWJujhfiSRV0jtmoRL_gg4Q14JN4dQ',
    approved: true,
    maintenanceBlocked: false,
  },
  {
    id: 'veh_11',
    name: 'Scooter Activa 125',
    type: '2-Wheeler',
    year: 2023,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    rateDay: 25,
    rateWeek: 150,
    rateMonth: 500,
    status: 'Available',
    plateNo: 'SUR-11-AA-9999',
    agencyId: 'agency_1',
    agencyName: 'Elite Motors',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC4__3KiFMk9jZIF-oDwvUYB98vS-8lXJ3yPqki1gUog09o5bBEVO_gLPbYsoO1NutExlfb93VzGS0oxrRXKudLqofszHW8UGNQUVwmbyc9N0zpPnPKIJVnfw94-uf3ChPdABFyne0IB0X_xMr6CaRJTgJ18uDL_k8T8Y8mt3TN28aQv_VoOWtHSShs_Fua_SH64tHNRC8w4zvJRjM1YvhsqCRf0-GMZ-BevQQ9WkOk_GqJdjgMZi3wMbtGyYXsfga46Es5lxkLeUgo',
    approved: true,
    maintenanceBlocked: false,
  }
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user_1',
    name: 'Marcus Miller',
    email: 'marcus.m@rentigo.com',
    phone: '+1 (555) 019-2831',
    role: 'admin',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBwo8cjB8-UcS1Th3hvmvvwGLWloQ8QFlQvSoV9OHQqS8ZBQqrW-jor_tmNR80HxVuyQP8JxLcbFrSrwHP4S5hrradXiiIV42SuvP0BjAVNp1mC5PpKhSQZ1Bul4IEupgZtzSmb8J2IbCSx_w5BrQqMfqkVVHAYuDoPGubZ0KYj0mplzvXbj0EYOSCoRWGPpfRm-3fNwi3Lbndvlz157y7N0M-OS66F78gUSeTp_gDD2W3ghD3HHb3psZo8UCrjN-N9b0xyg64nxNrJ'
  },
  {
    id: 'user_2',
    name: 'Sarah Kincaid',
    email: 's.kincaid@agency-lux.com',
    phone: '+1 (555) 488-2041',
    role: 'agency',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDfoe58PB6L8yhBxUYJn41xf2QT_tTjaPL05a_WJLuYZAiD0hJWWFH3OE6zwhXyQBLmVa4qyupopNDvsdKdLGaJRScv39Xn8ugoc0hKkIjD5OI3Re2p3Y0-EDWbv_0vyFRu8jMMQfNMOi6iUTSGM5MWnSWtz0U3pQleP9IMm6osNTKsCdmR8t8UC_UqS5ryjNNsQvChsdCOsVPyxiYd8ik3-GFFj4yXbya-w4z6VX3z90IqMLSbQeASRrli5cFSaGTFfdzoNEuuj58r'
  },
  {
    id: 'user_3',
    name: 'David Ling',
    email: 'd.ling@gmail.com',
    phone: '+1 (555) 712-0399',
    role: 'customer',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCSvprKEBGKRmJv-rlF3Nzotsmpq6L2OHo86MGTZzjWoY3O7eH8b2iggG7gacI6PCq_9OXmBC0Qphg1taPlQ_4C3WHi-KjSC-uXfMddFCt9qW3avCDIn0ZCL3QzdBBDqu-8zRUADO13kES3A42mpOa9X7DPbLOgxce0kYO6zn10-NfmxhzNIL6dy426HZ0p24Oe0OZOaT0s4Q8N8-4TGzgznywkP0dNq8AszrcxVGtcUOT18sRFCLk9yLPo7ETHk3uUM4o9yYWH5cXA'
  },
  {
    id: 'user_4',
    name: 'Robert Janson',
    email: 'robert.j@agency-elite.com',
    phone: '+1 (555) 655-4299',
    role: 'agency',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBXcCUOQyxskpPP_wfJ0STZz4N0QemaAGUJhkZ1ijD3uHMZ8FbtwdW1uca9g1kL_x6G2s5qI-Ly8YWzbjsDSDkSvyisRyiAJoyiEVK8kjyLsPwiriQRYtJYCOAvLDDA-uFpH1U1y0sK4TeHVYLy6DPaeq9UJe_OT4fexvS8gHLzS8-kz7A8D7sNe5ykIRfIyayLOoS3lqt11kJj-aU4l_6I5Y-eewzkzlERijhf43ukQdN-FUAigqj0tK5BUNZafRvKmXO4NQ1kPLJ_'
  },
  {
    id: 'user_5',
    name: 'Marcus Thompson',
    email: 'demo@rentigo.com',
    phone: '+1 (555) 012-3456',
    role: 'customer',
    dob: '1987-11-20',
    gender: 'male',
    address: '452 Corporate Way, Penthouse B',
    city: 'New York',
    zip: '10001',
    license: 'ABC123456789',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDUHmr1LDxHwY9lfi2-2ogj0MCOzeO9abyzvIo8ENgrfX1CfFhAMJ1ASKkbmNg_GfAOoES6CNaYrCUnGITKWeOVVS5qembWeY2eBXF1wC_8L3JgyHdpn2_zrels5QncFGAJv-8gEq_1ovtM15Xa3HQ9fNuNPTiGy4yFqOwjGGVo0QOShWLhg-TFZ6YxjMZge2zegjUgW1x6glYD5mzpuqf-keuzuC-15ALR9GIJMqHaPCH5mzDvCDD-YF8a-c3hq6-iybiM3zSF1Y6k'
  }
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'book_1',
    customerId: 'user_5',
    customerName: 'Marcus Thompson',
    customerPhone: '+1 (555) 012-3456',
    customerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDUHmr1LDxHwY9lfi2-2ogj0MCOzeO9abyzvIo8ENgrfX1CfFhAMJ1ASKkbmNg_GfAOoES6CNaYrCUnGITKWeOVVS5qembWeY2eBXF1wC_8L3JgyHdpn2_zrels5QncFGAJv-8gEq_1ovtM15Xa3HQ9fNuNPTiGy4yFqOwjGGVo0QOShWLhg-TFZ6YxjMZge2zegjUgW1x6glYD5mzpuqf-keuzuC-15ALR9GIJMqHaPCH5mzDvCDD-YF8a-c3hq6-iybiM3zSF1Y6k',
    vehicleId: 'veh_3',
    vehicleName: 'Mercedes Benz C-Class',
    vehicleImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAeVr8BLXp6g3Bz9DCMJc5bkAt6sF_9Qq1a3CbpYDbIWnU7IM-XqYkAdPgnihOML3_J3Ho6YSK_JNX2xTh1UtGUsgr0vDAffS76cp0BIayUzFWtT7DwUd4doFi_f25PgctsB9ypTSRh-AdIX6TB61QA_9IxKtrDZZzQI24B4MNDUauGWFspvh0E3O9amd6ttRB4s0goQUxgpysMo1FY6ZpLnsY0PnJXTzeZAZ7b_RnEXodF8WcujQr1DrF17HydxscZHtIzR1GJANxO',
    fuelType: 'Hybrid',
    startDate: '2026-06-15',
    endDate: '2026-06-19',
    durationDays: 4,
    totalAmount: 560,
    status: 'Pending',
    agencyId: 'agency_1',
    dateSubmitted: '2026-06-03'
  },
  {
    id: 'book_2',
    customerId: 'user_3',
    customerName: 'Sarah Jenkins',
    customerPhone: '+1 (555) 987-6543',
    customerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCFYoRHrOSBVOSNQSVMxxkeBp-WS5046rqhRnI8tRcHLNo6Vuz7jrhHaVB0ZVIPQjM_40UEEl9yp1lIecj74pxCXDA6iYCUn2J4bsTxFsoRZmHt6V9LaCzea4LcCStEjYyzMktYRBSAgJA5suJ6toCaYSeku517-ZwbVwV5he0G8L5CFTKkzCR9-EeUYgG1FAw0cUxL93ed-mFblXedlRhnAr-uVi5XRQK0DBAJAqgQrZKpxWZALwIoUdhYJSptjWHSWL9vy_3VRXV7',
    vehicleId: 'veh_7',
    vehicleName: 'Tesla Model Y',
    vehicleImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB1Oxr27qU3y8EP3O3wd5tN-ND3qaO6RxoXAEwl0H3bsd15TEcDxoXJJQV_q9Pa5eqC-2tmF6dqORoEQ6yXvPgSsXua1JfoK_C_g_MlCNUshUC6LC68yxIyH6-yxrIGtCd-ON5obKIcf_jY7XbzML3LAozjuyiQT2uh4YVrnzjcxKynjeVdcbgXXZjzTqpFK7DzcDuYR4EExUU3gq49iU7tnDKjc96aiT2s--MOkRPC4qnHzfS7tqiSh81rUR0gshqgM1a0DpB0fqDo',
    fuelType: 'Electric',
    startDate: '2026-06-05',
    endDate: '2026-06-08',
    durationDays: 3,
    totalAmount: 425,
    status: 'Approved',
    agencyId: 'agency_1',
    dateSubmitted: '2026-06-01'
  },
  {
    id: 'book_3',
    customerId: 'user_3',
    customerName: 'David Wilson',
    customerPhone: '+1 (555) 444-2211',
    customerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAgXf3ILU4iLwQjtr2hRCRu9dlQpbaXF2kX9lvLbwOqgYlHqGx6VFFwq4W0YoI0zySyXCmhe_xrqDr-QRtIN_eOeiIez6Nl8iIrO71kjv0DrCW485tJdO9T2BEnGnWJFOsS4GYRBWNd89Oqtq1iLkbt3IyPRbMx0mPsUQIG9gVl_TLHUQ6doI2dLNw4dyry9tYYNWhsvU-euMtzphE4VST7tRtLKZmZ7vl5zSoAbNDvr3ErM1hFJ76pWVtGClO_YDewYZFyebzsK9Au',
    vehicleId: 'veh_2',
    vehicleName: 'Range Rover Sport',
    vehicleImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBUslbiyxEXtoZS3TIKbKrakBQAhk6EpN20RjLvfrPZNRGbH1-ZJwf6hO33N0r5hICxWz8pofOhAXaVQ-KbxvbJa-mAkUUBrRCQdwMofvgiieGu7OvkAoeqlX1uVxzIIeAiUnu0IkwZyMCQ81hxoO3ufporqixnLGw6RtblAYkfuG6JhuPwAblMkRcbNFUu5AJIEZ-CYr3sakNsAv-RM0JbIdF4vOWOhHRvZcArHd-m3E6rY_lLj7XPykAx-b8QOPK5L8xOrmn7iXkk',
    fuelType: 'Diesel',
    startDate: '2026-05-20',
    endDate: '2026-05-21',
    durationDays: 1,
    totalAmount: 350,
    status: 'Rejected',
    agencyId: 'agency_3',
    dateSubmitted: '2026-05-18'
  }
];

export const INITIAL_MAINTENANCE: Maintenance[] = [
  {
    id: 'maint_1',
    vehicleId: 'veh_4',
    vehicleName: 'BMW 5 Series',
    plateNo: 'V-8821',
    vehicleImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAr2Yvuy1h_uVWDigpHebt280CDavg9BKJj8KQm5x3IbWPn9dI5cfwuXgvshhTrACd9Xe0a9qON_PRFtGv4N0ualwVFHbpTLa_w3NuK8Ud4cNJWtLhwMSEpoi2wW5ZkMg8SiD_xv1igIf_Eok_CcM0fCOPAbBlCzTa7nWzLxBiB4nJK2BQUzpyq-4UM_tZFbYCXFSSaNQlbwovfqMD-3E8mXkg2JegV6fQjnU6Cd8fJRt0Fr173fGHq71wQ0B8WbkmYUmNICZsbOAhs',
    serviceType: 'Annual Inspection',
    priority: 'routine',
    serviceDate: '2026-05-12',
    estimatedCost: 150,
    location: 'Rentigo Authorized Hub IV, Financial District',
    description: 'General system diagnostics and software updates.',
    status: 'Overdue'
  },
  {
    id: 'maint_2',
    vehicleId: 'veh_5',
    vehicleName: 'Audi Q7',
    plateNo: 'V-7422',
    vehicleImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBrT6m7yN-hAcivmUKdXYg-D9ysdEzMEGjpXVr1MtLtghuLzoOMYgtz-6004fokDnUh9zAe57JoEQ80fpBlu0bzd1nf4F0D_NdvO31HOCdtI0s0_6r02-eXYSVWnQxMbY-Nkl9REU8FeUYXaDrjS66xbzKg1B0LZcNTbpJBo5PkAcTMSyoc5tUTqb7zE-68B--7yTpzWhebWWJTae9ym8udvvaFgHHH0hWIrNm2oJo0hEOVrwYkFtggxG-aDumyiCIs8aYiRmPHTXeF',
    serviceType: 'Oil Change',
    priority: 'medium',
    serviceDate: '2026-06-01',
    estimatedCost: 85,
    location: 'Surat Tech Park Diagnostics Lab',
    description: 'Routine fluid flushing and engine filters replacement.',
    status: 'In Progress'
  },
  {
    id: 'maint_3',
    vehicleId: 'veh_1',
    vehicleName: 'Tesla Model 3',
    plateNo: 'ABC-1234',
    vehicleImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC842OrLsEaVFsCsJWoRKHllgwFNZ_-E-ZsVWgoIDJvVnbclSU-OYa09o7S-aHW-xFpKXc-7moz_Y9kxMtpS03Ns0J1O0rHK7KYHfItVnHaBsH7AzDNWSe7OOMQLgSxDc-SKb54YYkfXjSKYTgX70hJLE80LZ9GDaQctgR3LE73iDj7hZD_7bUZsVL2uBK3JYF9eur73db_OJWduIWkso-rdz0gsi7w9-D-DRuRuO1czCvScKMWhLscWwIo4H1Pn2f3rz40uRIw-7XN',
    serviceType: 'Brake Service',
    priority: 'critical',
    serviceDate: '2026-06-12',
    estimatedCost: 320,
    location: 'Rentigo Premium Service Zone 1',
    description: 'Brake pads replacement and hydraulic line flush.',
    status: 'Scheduled'
  }
];

export const INITIAL_PRICING_CLASSES: PricingClass[] = [
  { name: 'Economy', baseDay: 45, rateWeekDiscount: 15, rateMonthDiscount: 30, units: 124, active: true, category: 'Standard Fleet' },
  { name: 'SUV / Crossover', baseDay: 85, rateWeekDiscount: 10, rateMonthDiscount: 25, units: 86, active: true, category: 'Utility & Adventure' },
  { name: 'Luxury', baseDay: 150, rateWeekDiscount: 5, rateMonthDiscount: 20, units: 32, active: true, category: 'Premium & Exotic' },
  { name: '2-Wheeler', baseDay: 25, rateWeekDiscount: 20, rateMonthDiscount: 40, units: 45, active: false, category: 'Compact Transit' }
];

export const INITIAL_PRICING_RULES: PricingRule[] = [
  {
    id: 'rule_1',
    name: 'Summer Peak Season',
    surgePercent: 25,
    startDate: '2026-06-15',
    endDate: '2026-08-31',
    applicableClass: 'All Classes',
    active: true,
    iconName: 'calendar_month',
    notes: "Global application excluding 'Long-term' contracts."
  },
  {
    id: 'rule_2',
    name: 'Global Tech Expo 2026',
    surgePercent: 40,
    startDate: '2026-10-10',
    endDate: '2026-10-14',
    applicableClass: 'Luxury',
    active: true,
    iconName: 'celebration',
    notes: 'Luxury and Executive categories only in Surat City limits.'
  }
];

export const INITIAL_ALERTS: SystemAlert[] = [
  {
    id: 'alert_1',
    type: 'unauthorized',
    title: 'Unauthorized Vehicle Access',
    message: 'Vehicle ID: #LX-8829 detected out of geo-fence in Zone 4.',
    dateSubmitted: '2 minutes ago'
  },
  {
    id: 'alert_2',
    type: 'warning',
    title: 'Booking Surge Alert',
    message: 'Economy fleet at 95% capacity in North Surat sector.',
    dateSubmitted: '15 minutes ago'
  },
  {
    id: 'alert_3',
    type: 'lag',
    title: 'Payment Gateway Lag',
    message: 'Transaction delays observed for Agency ID: #AG-992.',
    dateSubmitted: '42 minutes ago'
  }
];
